#Requires AutoHotkey v2.0
#SingleInstance Force

; =============================================================
;  komorebi.ahk — generated by dotfiles-installer
;
;  Keybinding preset: set by installer
;    Focus  (select window) : {{AHK_MOD}} + {{SEL_L}} / {{SEL_D}} / {{SEL_U}} / {{SEL_R}}
;    Move   (relocate tile) : {{AHK_MOVE_MOD}} + {{MOV_L}} / {{MOV_D}} / {{MOV_U}} / {{MOV_R}}
;    Resize                 : Left-Win + Arrow keys (always)
;    Workspaces             : {{AHK_MOD}} + 1-6
; =============================================================

Komorebic(cmd) {
    Run(Format("komorebic.exe {}", cmd), , "Hide")
}

KomorebicSync(cmd) {
    RunWait(Format("komorebic.exe {}", cmd), , "Hide")
}

RunIfNotRunning(processName, target) {
    if ProcessExist(processName) {
        return
    }

    try {
        Run(target, , "Hide")
    }
}

ResolveFlowLauncherCommand() {
    localAppData := EnvGet("LOCALAPPDATA")
    primary := localAppData "\FlowLauncher\Flow.Launcher.exe"

    if FileExist(primary) {
        return Chr(34) . primary . Chr(34)
    }

    Loop Files localAppData "\FlowLauncher\app-*\Flow.Launcher.exe", "F" {
        return Chr(34) . A_LoopFileFullPath . Chr(34)
    }

    return "Flow.Launcher.exe"
}

CloseProcessByName(processName) {
    while (pid := ProcessExist(processName)) {
        try {
            ProcessClose(pid)
        } catch {
            break
        }
        Sleep(100)
    }
}

StartDesktopEnvironment() {
    RunIfNotRunning("komorebi.exe", "komorebic.exe start --masir")
    RunIfNotRunning("yasb.exe", "yasb.exe")
    RunIfNotRunning("Flow.Launcher.exe", ResolveFlowLauncherCommand())
}

StopDesktopEnvironment(*) {
    CloseProcessByName("Flow.Launcher.exe")
    CloseProcessByName("yasb.exe")
    KomorebicSync("stop --masir")
}

CloseDesktopEnvironment() {
    StopDesktopEnvironment()
    ExitApp
}

OnExit(StopDesktopEnvironment)
StartDesktopEnvironment()

; Exit the full desktop environment + this script
^!+k:: CloseDesktopEnvironment()

; ── Focus (select which window is active) ─────────────────────
{{AHK_MOD}}{{SEL_L}}:: Komorebic("focus left")
{{AHK_MOD}}{{SEL_D}}:: Komorebic("focus down")
{{AHK_MOD}}{{SEL_U}}:: Komorebic("focus up")
{{AHK_MOD}}{{SEL_R}}:: Komorebic("focus right")

; ── Move (relocate window to a different tile) ────────────────
{{AHK_MOVE_MOD}}{{MOV_L}}:: Komorebic("move left")
{{AHK_MOVE_MOD}}{{MOV_D}}:: Komorebic("move down")
{{AHK_MOVE_MOD}}{{MOV_U}}:: Komorebic("move up")
{{AHK_MOVE_MOD}}{{MOV_R}}:: Komorebic("move right")
{{AHK_MOD_SHIFT}}e:: Komorebic("promote")

; ── Resize (Left-Win + arrows = small, Left-Win + WASD = large) ──
<#Right:: Komorebic("resize-axis horizontal increase 0.05")
<#Left::  Komorebic("resize-axis horizontal decrease 0.05")
<#Up::    Komorebic("resize-axis vertical decrease 0.05")
<#Down::  Komorebic("resize-axis vertical increase 0.05")
<#d::     Komorebic("resize-axis horizontal increase 0.10")
<#a::     Komorebic("resize-axis horizontal decrease 0.10")
<#w::     Komorebic("resize-axis vertical decrease 0.10")
<#s::     Komorebic("resize-axis vertical increase 0.10")

; ── Window state ──────────────────────────────────────────────
<!v::     Komorebic("toggle-float")
<!f::     Komorebic("toggle-fullscreen")
#f::      Send("{F11}")
#^!w::    Komorebic("toggle-monocle")
<#c::     Komorebic("close")
<#m::     Komorebic("minimize")

; ── Layout cycling ────────────────────────────────────────────
<!z:: Komorebic("cycle-layout next")
<!c:: Komorebic("cycle-monitor next")
<!x:: Komorebic("focus-last-workspace")

; ── Workspaces (focus) ────────────────────────────────────────
FocusWS(ws) {
    Komorebic("focus-workspace " . ws)
}
MoveFollow(ws) {
    KomorebicSync("move-to-workspace " . ws)
    Komorebic("focus-workspace " . ws)
}
MoveSilent(ws) {
    Komorebic("move-to-workspace " . ws)
}

{{AHK_MOD}}1:: FocusWS("0")
{{AHK_MOD}}2:: FocusWS("1")
{{AHK_MOD}}3:: FocusWS("2")
{{AHK_MOD}}4:: FocusWS("3")
{{AHK_MOD}}5:: FocusWS("4")
{{AHK_MOD}}6:: FocusWS("5")

; Cycle workspaces
{{AHK_MOD}}q::     Komorebic("cycle-workspace previous")
{{AHK_MOD}}e::     Komorebic("cycle-workspace next")
{{AHK_MOD}}Right:: Komorebic("cycle-workspace next")
{{AHK_MOD}}Left::  Komorebic("cycle-workspace previous")

; ── Move window to workspace ───────────────────────────────────
; MoveFollow  (#+ number): moves window AND follows it to that workspace
; MoveSilent (!+ number): moves window silently, stay on current workspace
#+1:: MoveFollow("0")
#+2:: MoveFollow("1")
#+3:: MoveFollow("2")
#+4:: MoveFollow("3")
#+5:: MoveFollow("4")
#+6:: MoveFollow("5")

{{AHK_MOD_SHIFT}}1:: MoveSilent("0")
{{AHK_MOD_SHIFT}}2:: MoveSilent("1")
{{AHK_MOD_SHIFT}}3:: MoveSilent("2")
{{AHK_MOD_SHIFT}}4:: MoveSilent("3")
{{AHK_MOD_SHIFT}}5:: MoveSilent("4")
{{AHK_MOD_SHIFT}}6:: MoveSilent("5")

; ── Named workspaces (optional — uncomment and rename as needed) ──
; {{AHK_MOD}}c:: Komorebic("focus-named-workspace Comms")
; {{AHK_MOD}}t:: Komorebic("focus-named-workspace ToDo")
; {{AHK_MOD_SHIFT}}c:: Komorebic("move-to-named-workspace Comms")
; {{AHK_MOD_SHIFT}}t:: Komorebic("move-to-named-workspace ToDo")

; ── App launchers (Win key) ────────────────────────────────────
#q:: Run("pwsh -NoProfile -Command wezterm", , "Hide")   ; Win+Q → terminal
#e:: Run("explorer.exe")                                  ; Win+E → file explorer
#b:: Run("pwsh -NoProfile -Command explorer shell:RecycleBinFolder", , "Hide")
; #z:: Run("C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Firefox.lnk")  ; Win+Z → browser
